In [8]:
!python3 --version
import numpy
print("NumPy version", numpy.version.version)
import tensorflow
print("TensorFlow version", tensorflow.__version__)
import pandas
print("Pandas version", pandas.__version__)
import imblearn
print("ImbLearn version", imblearn.__version__)

Python 3.10.12
NumPy version 1.25.2
TensorFlow version 2.15.0
Pandas version 2.0.3
ImbLearn version 0.10.1


In [ ]:
from google.colab import drive as dr
dr.mount('/content/drive')

import numpy as np
import pandas as pd

Mounted at /content/drive


In [ ]:
dat1 = pd.read_csv('drive/My Drive/Internship/2024-Summer/Dataset/data1.csv')
dat2 = pd.read_csv('drive/My Drive/Internship/2024-Summer/Dataset/data2.csv')
dat3 = pd.read_csv('drive/My Drive/Internship/2024-Summer/Dataset/data3.csv')

In [ ]:
"Data1", dat1, "\nData2", dat2, "\nData3", dat3

('Data1',
         Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
 0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
 1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
 2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
 3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
 4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   
 ...                 ...     ...       ...        ...   ...     ...     ...   
 253675              0.0     1.0       1.0        1.0  45.0     0.0     0.0   
 253676              1.0     1.0       1.0        1.0  18.0     0.0     0.0   
 253677              0.0     0.0       0.0        1.0  28.0     0.0     0.0   
 253678              0.0     1.0       0.0        1.0  23.0     0.0     0.0   
 253679              1.0     1.0       1.0        1.0  25.0     0.0     0.0   
 
         HeartDiseaseorAttack  PhysActiv

In [ ]:
'Data1', len(dat1[dat1['Diabetes_binary']==0.0]), len(dat1[dat1['Diabetes_binary']==1.0]), '\nData2', len(dat2[dat2['Diabetes_binary']==0.0]), len(dat2[dat2['Diabetes_binary']==1.0]), '\nData3', len(dat3[dat3['Diabetes_012']==0.0]), len(dat3[dat3['Diabetes_012']==1.0])

('Data1', 218334, 35346, '\nData2', 35346, 35346, '\nData3', 213703, 4631)

In [ ]:
#As we observe only Data2 has balanced dataset where Data2 and Data3 has imbalance.

In [ ]:
dat1 = dat1.astype(int)
dat2 = dat2.astype(int)
dat3 = dat3.astype(int)

In [ ]:
dat1, dat2, dat3

(        Diabetes_binary  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
 0                     0       1         1          1   40       1       0   
 1                     0       0         0          0   25       1       0   
 2                     0       1         1          1   28       0       0   
 3                     0       1         0          1   27       0       0   
 4                     0       1         1          1   24       0       0   
 ...                 ...     ...       ...        ...  ...     ...     ...   
 253675                0       1         1          1   45       0       0   
 253676                1       1         1          1   18       0       0   
 253677                0       0         0          1   28       0       0   
 253678                0       1         0          1   23       0       0   
 253679                1       1         1          1   25       0       0   
 
         HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyH

In [ ]:
#3rd dataset has the prediabetes as one of class of diabetes but we want to classify between diabetes and normal so let's put prediabetes to normal

In [ ]:
colD = dat3['Diabetes_012']
for i in range(len(colD)):
  if colD[i]==1:
    colD[i]=0
  elif colD[i]==2:
    colD[i]=1

In [ ]:
dat3

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0                  0       1         1          1   40       1       0   
1                  0       0         0          0   25       1       0   
2                  0       1         1          1   28       0       0   
3                  0       1         0          1   27       0       0   
4                  0       1         1          1   24       0       0   
...              ...     ...       ...        ...  ...     ...     ...   
253675             0       1         1          1   45       0       0   
253676             1       1         1          1   18       0       0   
253677             0       0         0          1   28       0       0   
253678             0       1         0          1   23       0       0   
253679             1       1         1          1   25       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                          0             0       0  ...              1   
1                          0             1       0  ...              0   
2                          0             0       1  ...              1   
3                          0             1       1  ...              1   
4                          0             1       1  ...              1   
...                      ...           ...     ...  ...            ...   
253675                     0             0       1  ...              1   
253676                     0             0       0  ...              1   
253677                     0             1       1  ...              1   
253678                     0             0       1  ...              1   
253679                     1             1       1  ...              1   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  \
0                 0        5        18        15         1    0    9   
1                 1        3         0         0         0    0    7   
2                 1        5        30        30         1    0    9   
3                 0        2         0         0         0    0   11   
4                 0        2         3         0         0    0   11   
...             ...      ...       ...       ...       ...  ...  ...   
253675            0        3         0         5         0    1    5   
253676            0        4         0         0         1    0   11   
253677            0        1         0         0         0    0    2   
253678            0        3         0         0         0    1    7   
253679            0        2         0         0         0    0    9   

        Education  Income  
0               4       3  
1               6       1  
2               4       8  
3               3       6  
4               5       4  
...           ...     ...  
253675          6       7  
253676          2       4  
253677          5       2  
253678          5       1  
253679          6       2  

[253680 rows x 22 columns]

In [ ]:
y_dat1 = dat1['Diabetes_binary']
y_dat2 = dat2['Diabetes_binary']
y_dat3 = dat3['Diabetes_012']
y_dat1

0         0
1         0
2         0
3         0
4         0
         ..
253675    0
253676    1
253677    0
253678    0
253679    1
Name: Diabetes_binary, Length: 253680, dtype: int64

In [ ]:
x_dat1 = dat1.drop('Diabetes_binary', axis=1)
x_dat2 = dat2.drop('Diabetes_binary', axis=1)
x_dat3 = dat3.drop('Diabetes_012', axis=1)
x_dat1

HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0            1         1          1   40       1       0   
1            0         0          0   25       1       0   
2            1         1          1   28       0       0   
3            1         0          1   27       0       0   
4            1         1          1   24       0       0   
...        ...       ...        ...  ...     ...     ...   
253675       1         1          1   45       0       0   
253676       1         1          1   18       0       0   
253677       0         0          1   28       0       0   
253678       1         0          1   23       0       0   
253679       1         1          1   25       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                          0             0       0        1  ...   
1                          0             1       0        0  ...   
2                          0             0       1        0  ...   
3                          0             1       1        1  ...   
4                          0             1       1        1  ...   
...                      ...           ...     ...      ...  ...   
253675                     0             0       1        1  ...   
253676                     0             0       0        0  ...   
253677                     0             1       1        0  ...   
253678                     0             0       1        1  ...   
253679                     1             1       1        0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
0                   1            0        5        18        15         1   
1                   0            1        3         0         0         0   
2                   1            1        5        30        30         1   
3                   1            0        2         0         0         0   
4                   1            0        2         3         0         0   
...               ...          ...      ...       ...       ...       ...   
253675              1            0        3         0         5         0   
253676              1            0        4         0         0         1   
253677              1            0        1         0         0         0   
253678              1            0        3         0         0         0   
253679              1            0        2         0         0         0   

        Sex  Age  Education  Income  
0         0    9          4       3  
1         0    7          6       1  
2         0    9          4       8  
3         0   11          3       6  
4         0   11          5       4  
...     ...  ...        ...     ...  
253675    1    5          6       7  
253676    0   11          2       4  
253677    0    2          5       2  
253678    1    7          5       1  
253679    0    9          6       2  

[253680 rows x 21 columns]

In [ ]:
from sklearn.model_selection import train_test_split as tts

In [ ]:
x_dat1_imb, x_dat1_test, y_dat1_imb, y_dat1_test = tts(x_dat1, y_dat1, test_size=0.3, random_state=42)
x_dat2_bal, x_dat2_test, y_dat2_bal, y_dat2_test = tts(x_dat2, y_dat2, test_size=0.3, random_state=42)
x_dat3_imb, x_dat3_test, y_dat3_imb, y_dat3_test = tts(x_dat3, y_dat3, test_size=0.3, random_state=42)

In [ ]:
len(y_dat1_imb), len(y_dat1_test)

(177576, 76104)

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
sm = SMOTE(random_state=0)

In [ ]:
sum(y_dat1_imb==0), sum(y_dat1_imb==1)

(152729, 24847)

In [ ]:
y_dat1, y_dat1.ravel()

(0         0
 1         0
 2         0
 3         0
 4         0
          ..
 253675    0
 253676    1
 253677    0
 253678    0
 253679    1
 Name: Diabetes_binary, Length: 253680, dtype: int64,
 array([0, 0, 0, ..., 0, 0, 1]))

In [ ]:
x_dat1_bal, y_dat1_bal = sm.fit_resample(x_dat1_imb, y_dat1_imb)
x_dat3_bal, y_dat3_bal = sm.fit_resample(x_dat3_imb, y_dat3_imb)
sum(y_dat1_bal==0), sum(y_dat1_bal==1)

(152729, 152729)

In [ ]:
import tensorflow as tf
from tensorflow import keras as ker
from tensorflow.keras.models import Model
import tensorflow.keras.layers as lay

In [ ]:
x_dat1_bal.iloc[0,:], "No. of features", len(x_dat1_bal.iloc[0,:])

(HighBP                   1
 HighChol                 1
 CholCheck                1
 BMI                     35
 Smoker                   0
 Stroke                   0
 HeartDiseaseorAttack     0
 PhysActivity             1
 Fruits                   1
 Veggies                  1
 HvyAlcoholConsump        0
 AnyHealthcare            1
 NoDocbcCost              0
 GenHlth                  5
 MentHlth                 0
 PhysHlth                14
 DiffWalk                 1
 Sex                      0
 Age                     12
 Education                3
 Income                   1
 Name: 0, dtype: int64,
 'No. of features',
 21)

In [ ]:
#Let's build neural network model

In [ ]:
inp_layer = lay.Input(shape=(21, )) #Input layer

int_layer = lay.Dense(30, activation='linear')(inp_layer) #Intermediate layer

out_layer = lay.Dense(1, activation='sigmoid')(int_layer) #Output layer

NN = Model(inputs=inp_layer, outputs=out_layer)

In [ ]:
NN.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 21)]              0         
                                                                 
 dense_2 (Dense)             (None, 30)                660       
                                                                 
 dense_3 (Dense)             (None, 1)                 31        
                                                                 
Total params: 691 (2.70 KB)
Trainable params: 691 (2.70 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
NN.compile(optimizer=ker.optimizers.Adam(learning_rate=0.01), loss='binary_crossentropy', metrics='accuracy')

In [ ]:
#Performance of model on 1st dataset

In [ ]:
NN.fit(x_dat1_bal, y_dat1_bal, epochs=15)

Epoch 1/15
9546/9546 [==============================] - 18s 2ms/step - loss: 0.5401 - accuracy: 0.7280
Epoch 2/15
9546/9546 [==============================] - 19s 2ms/step - loss: 0.5295 - accuracy: 0.7340
Epoch 3/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5283 - accuracy: 0.7340
Epoch 4/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5287 - accuracy: 0.7343
Epoch 5/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5286 - accuracy: 0.7346
Epoch 6/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5284 - accuracy: 0.7346
Epoch 7/15
9546/9546 [==============================] - 19s 2ms/step - loss: 0.5282 - accuracy: 0.7346
Epoch 8/15
9546/9546 [==============================] - 18s 2ms/step - loss: 0.5280 - accuracy: 0.7341
Epoch 9/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5278 - accuracy: 0.7352
Epoch 10/15
9546/9546 [==============================] - 17s 2ms/step - l

In [ ]:
NN.evaluate(x_dat1_test, y_dat1_test)

2379/2379 [==============================] - 5s 2ms/step - loss: 0.5234 - accuracy: 0.7404


[0.5234265923500061, 0.7403684258460999]

In [ ]:
#Performance of model on 2nd dataset

In [ ]:
NN.fit(x_dat2_bal, y_dat2_bal, epochs=15)

Epoch 1/15
1547/1547 [==============================] - 5s 3ms/step - loss: 0.5394 - accuracy: 0.7300
Epoch 2/15
1547/1547 [==============================] - 4s 3ms/step - loss: 0.5284 - accuracy: 0.7397
Epoch 3/15
1547/1547 [==============================] - 6s 4ms/step - loss: 0.5272 - accuracy: 0.7393
Epoch 4/15
1547/1547 [==============================] - 5s 3ms/step - loss: 0.5272 - accuracy: 0.7395
Epoch 5/15
1547/1547 [==============================] - 5s 3ms/step - loss: 0.5254 - accuracy: 0.7387
Epoch 6/15
1547/1547 [==============================] - 6s 4ms/step - loss: 0.5249 - accuracy: 0.7402
Epoch 7/15
1547/1547 [==============================] - 5s 3ms/step - loss: 0.5245 - accuracy: 0.7409
Epoch 8/15
1547/1547 [==============================] - 5s 3ms/step - loss: 0.5231 - accuracy: 0.7411
Epoch 9/15
1547/1547 [==============================] - 7s 4ms/step - loss: 0.5227 - accuracy: 0.7435
Epoch 10/15
1547/1547 [==============================] - 6s 4ms/step - loss: 0.523

In [ ]:
NN.evaluate(x_dat2_test, y_dat2_test)

663/663 [==============================] - 3s 5ms/step - loss: 0.5142 - accuracy: 0.7447


[0.5141873359680176, 0.7447189688682556]

In [ ]:
#Performance of model on 3rd dataset

In [ ]:
NN.fit(x_dat3_bal, y_dat3_bal, epochs=15)

Epoch 1/15
9546/9546 [==============================] - 33s 3ms/step - loss: 0.5283 - accuracy: 0.7352
Epoch 2/15
9546/9546 [==============================] - 36s 4ms/step - loss: 0.5278 - accuracy: 0.7348
Epoch 3/15
9546/9546 [==============================] - 32s 3ms/step - loss: 0.5274 - accuracy: 0.7358
Epoch 4/15
9546/9546 [==============================] - 27s 3ms/step - loss: 0.5276 - accuracy: 0.7354
Epoch 5/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5278 - accuracy: 0.7351
Epoch 6/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5276 - accuracy: 0.7353
Epoch 7/15
9546/9546 [==============================] - 18s 2ms/step - loss: 0.5275 - accuracy: 0.7356
Epoch 8/15
9546/9546 [==============================] - 18s 2ms/step - loss: 0.5269 - accuracy: 0.7365
Epoch 9/15
9546/9546 [==============================] - 17s 2ms/step - loss: 0.5277 - accuracy: 0.7356
Epoch 10/15
9546/9546 [==============================] - 18s 2ms/step - l

In [ ]:
NN.evaluate(x_dat3_test, y_dat3_test)

2379/2379 [==============================] - 7s 3ms/step - loss: 0.5303 - accuracy: 0.7301


[0.5302519798278809, 0.7300798892974854]

In [ ]:
#----END OF WORK-------------

In [ ]:
#ANY CODE WRITTEN BELOW IS IRRELEVANT TO THIS WORK IT'S JUST SOME OF THE FAILED ATTEMPTS WHICH I USED WHEN I TRIED RBM.

In [ ]:
y_pred = NN.predict(x_dat1_test)

2379/2379 [==============================] - 3s 1ms/step


In [ ]:
y_dat1_test

(array([[1.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]], dtype=float32),
 219620    0
 132821    0
 151862    0
 139717    0
 239235    0
          ..
 58678     0
 203840    1
 206241    0
 53188     0
 53404     0
 Name: Diabetes_binary, Length: 76104, dtype: int64)

In [ ]:
colB2 = dat2['BMI']
for i in range(len(colB2)):
  colB2[i] = dec2bin(colB2[i], maxB)

colB3 = dat3['BMI']
for i in range(len(colB3)):
  colB3[i] = dec2bin(colB3[i], maxB)

In [ ]:
dat1, dat2, dat3

(        Diabetes_binary  HighBP  HighChol  CholCheck      BMI  Smoker  Stroke  \
 0                     0       1         1          1  0101000       1       0   
 1                     0       0         0          0  0011001       1       0   
 2                     0       1         1          1  0011100       0       0   
 3                     0       1         0          1  0011011       0       0   
 4                     0       1         1          1  0011000       0       0   
 ...                 ...     ...       ...        ...      ...     ...     ...   
 253675                0       1         1          1  0101101       0       0   
 253676                1       1         1          1  0010010       0       0   
 253677                0       0         0          1  0011100       0       0   
 253678                0       1         0          1  0010111       0       0   
 253679                1       1         1          1  0011001       0       0   
 
         Heart

In [ ]:
colG1 = dat1['GenHlth']
colG2 = dat2['GenHlth']
colG3 = dat3['GenHlth']

for i in range(len(colG1)):
  colG1[i] = dec2bin(colG1[i], maxG)

for i in range(len(colG2)):
  colG2[i] = dec2bin(colG2[i], maxG)

for i in range(len(colG3)):
  colG3[i] = dec2bin(colG3[i], maxG)

<ipython-input-16-8c6efd6bae8f>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colG1[i] = dec2bin(colG1[i], maxG)
<ipython-input-16-8c6efd6bae8f>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colG2[i] = dec2bin(colG2[i], maxG)
<ipython-input-16-8c6efd6bae8f>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colG3[i] = dec2bin(colG3[i], maxG)


In [ ]:
colM1 = dat1['MentHlth']
colM2 = dat2['MentHlth']
colM3 = dat3['MentHlth']

for i in range(len(colM1)):
  colM1[i] = dec2bin(colM1[i], maxM)

for i in range(len(colM2)):
  colM2[i] = dec2bin(colM2[i], maxM)

for i in range(len(colM3)):
  colM3[i] = dec2bin(colM3[i], maxM)

<ipython-input-17-e22b52218d30>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colM1[i] = dec2bin(colM1[i], maxM)
<ipython-input-17-e22b52218d30>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colM2[i] = dec2bin(colM2[i], maxM)
<ipython-input-17-e22b52218d30>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colM3[i] = dec2bin(colM3[i], maxM)


In [ ]:
colP1 = dat1['PhysHlth']
colP2 = dat2['PhysHlth']
colP3 = dat3['PhysHlth']

for i in range(len(colP1)):
  colP1[i] = dec2bin(colP1[i], maxP)

for i in range(len(colP2)):
  colP2[i] = dec2bin(colP2[i], maxP)

for i in range(len(colP3)):
  colP3[i] = dec2bin(colP3[i], maxP)

<ipython-input-18-92223d116fe6>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colP1[i] = dec2bin(colP1[i], maxP)
<ipython-input-18-92223d116fe6>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colP2[i] = dec2bin(colP2[i], maxP)
<ipython-input-18-92223d116fe6>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colP3[i] = dec2bin(colP3[i], maxP)


In [ ]:
colA1 = dat1['Age']
colA2 = dat2['Age']
colA3 = dat3['Age']

for i in range(len(colA1)):
  colA1[i] = dec2bin(colA1[i], maxA)

for i in range(len(colA2)):
  colA2[i] = dec2bin(colA2[i], maxA)

for i in range(len(colA3)):
  colA3[i] = dec2bin(colA3[i], maxA)

<ipython-input-19-d1f48795c931>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colA1[i] = dec2bin(colA1[i], maxA)
<ipython-input-19-d1f48795c931>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colA2[i] = dec2bin(colA2[i], maxA)
<ipython-input-19-d1f48795c931>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colA3[i] = dec2bin(colA3[i], maxA)


In [ ]:
colE1 = dat1['Education']
colE2 = dat2['Education']
colE3 = dat3['Education']

for i in range(len(colE1)):
  colE1[i] = dec2bin(colE1[i], maxE)

for i in range(len(colE2)):
  colE2[i] = dec2bin(colE2[i], maxE)

for i in range(len(colE3)):
  colE3[i] = dec2bin(colE3[i], maxE)

<ipython-input-20-e1837032b089>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colE1[i] = dec2bin(colE1[i], maxE)
<ipython-input-20-e1837032b089>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colE2[i] = dec2bin(colE2[i], maxE)
<ipython-input-20-e1837032b089>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colE3[i] = dec2bin(colE3[i], maxE)


In [ ]:
colI1 = dat1['Income']
colI2 = dat2['Income']
colI3 = dat3['Income']

for i in range(len(colI1)):
  colI1[i] = dec2bin(colI1[i], maxI)

for i in range(len(colI2)):
  colI2[i] = dec2bin(colI2[i], maxI)

for i in range(len(colI3)):
  colI3[i] = dec2bin(colI3[i], maxI)

<ipython-input-21-7787d174a0d4>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colI1[i] = dec2bin(colI1[i], maxI)
<ipython-input-21-7787d174a0d4>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colI2[i] = dec2bin(colI2[i], maxI)
<ipython-input-21-7787d174a0d4>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colI3[i] = dec2bin(colI3[i], maxI)


In [ ]:
dat1, dat2, dat3

(        Diabetes_binary  HighBP  HighChol  CholCheck      BMI  Smoker  Stroke  \
 0                     0       1         1          1  0101000       1       0   
 1                     0       0         0          0  0011001       1       0   
 2                     0       1         1          1  0011100       0       0   
 3                     0       1         0          1  0011011       0       0   
 4                     0       1         1          1  0011000       0       0   
 ...                 ...     ...       ...        ...      ...     ...     ...   
 253675                0       1         1          1  0101101       0       0   
 253676                1       1         1          1  0010010       0       0   
 253677                0       0         0          1  0011100       0       0   
 253678                0       1         0          1  0010111       0       0   
 253679                1       1         1          1  0011001       0       0   
 
         Heart

In [ ]:
dat1 = dat1.astype(str)
dat2 = dat2.astype(str)
dat3 = dat3.astype(str)

In [ ]:
print(dat1.iloc[0, :])
out = ""
for i in range(len(dat1.iloc[0, :])):
  out = out + dat1.iloc[0, i]
print(out)

Diabetes_binary               0
HighBP                        1
HighChol                      1
CholCheck                     1
BMI                     0101000
Smoker                        1
Stroke                        0
HeartDiseaseorAttack          0
PhysActivity                  0
Fruits                        0
Veggies                       1
HvyAlcoholConsump             0
AnyHealthcare                 1
NoDocbcCost                   0
GenHlth                     101
MentHlth                  10010
PhysHlth                  01111
DiffWalk                      1
Sex                           0
Age                        1001
Education                   100
Income                     0011
Name: 0, dtype: object
0111010100010000101010110010011111010011000011


In [ ]:
n = len(dat3)

In [ ]:
dat3.iloc[1, 4]

'0011001'

In [ ]:
#Let us keep 1st 7 columns to be visible nodes while the rest to be hidden nodes.

In [ ]:
V = []
H = []
for i in range(len(dat3)):
  #out = ""
  ls1 = []
  ls2 = []
  for j in range(len(dat3.iloc[i, :])):
    #out = out + dat3.iloc[i, j]
      for k in range(len(dat3.iloc[i, j])):
        if j<7:
          ls1.append(int(dat3.iloc[i, j][k]))
        else:
          ls2.append(int(dat3.iloc[i, j][k]))
  V.append(np.array(ls1))
  H.append(np.array(ls2))
  print(i*100/n)

len(V), len(H)

Streaming output truncated to the last 5000 lines.
98.02901292967518
98.02940712708924
98.02980132450331
98.03019552191738
98.03058971933145
98.03098391674551
98.03137811415957
98.03177231157363
98.0321665089877
98.03256070640177
98.03295490381583
98.0333491012299
98.03374329864396
98.03413749605802
98.03453169347209
98.03492589088616
98.03532008830022
98.03571428571429
98.03610848312834
98.03650268054241
98.03689687795648
98.03729107537055
98.03768527278461
98.03807947019868
98.03847366761273
98.0388678650268
98.03926206244087
98.03965625985494
98.040050457269
98.04044465468307
98.04083885209712
98.04123304951119
98.04162724692526
98.04202144433933
98.0424156417534
98.04280983916746
98.04320403658151
98.04359823399558
98.04399243140965
98.04438662882372
98.04478082623778
98.04517502365185
98.0455692210659
98.04596341847997
98.04635761589404
98.0467518133081
98.04714601072217
98.04754020813624
98.0479344055503
98.04832860296436
98.04872280037843
98.0491169977925
98.04951119520656
98.04

(253680, 253680)

In [ ]:
len(V), V[0:10]

(253680,
 [array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
         1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
         1, 1]),
  array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
         0, 1]),
  array([0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
         1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
         0, 0]),
  array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
         1, 0]),
  array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
         0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
         0, 0]),
  array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
      

In [ ]:
'''H = []
h = 5 #Size of hidden vector
np.random.seed(42)
for i in range(len(V)):
  #out = ""
  ls = []
  for j in range(h):
    x = np.random.random()
    if x>0.5:
      #out = out + '1'
      ls.append(1)
    else:
      #out = out + '0'
      ls.append(0)
  H.append(np.array(ls))
  print(i*100/len(V))'''

Streaming output truncated to the last 5000 lines.
98.02901292967518
98.02940712708924
98.02980132450331
98.03019552191738
98.03058971933145
98.03098391674551
98.03137811415957
98.03177231157363
98.0321665089877
98.03256070640177
98.03295490381583
98.0333491012299
98.03374329864396
98.03413749605802
98.03453169347209
98.03492589088616
98.03532008830022
98.03571428571429
98.03610848312834
98.03650268054241
98.03689687795648
98.03729107537055
98.03768527278461
98.03807947019868
98.03847366761273
98.0388678650268
98.03926206244087
98.03965625985494
98.040050457269
98.04044465468307
98.04083885209712
98.04123304951119
98.04162724692526
98.04202144433933
98.0424156417534
98.04280983916746
98.04320403658151
98.04359823399558
98.04399243140965
98.04438662882372
98.04478082623778
98.04517502365185
98.0455692210659
98.04596341847997
98.04635761589404
98.0467518133081
98.04714601072217
98.04754020813624
98.0479344055503
98.04832860296436
98.04872280037843
98.0491169977925
98.04951119520656
98.04

In [ ]:
len(H), H[0:10]

(253680,
 [array([0, 1, 1, 1, 0]),
  array([0, 0, 1, 1, 1]),
  array([0, 1, 1, 0, 0]),
  array([0, 0, 1, 0, 0]),
  array([1, 0, 0, 0, 0]),
  array([1, 0, 1, 1, 0]),
  array([1, 0, 0, 1, 1]),
  array([1, 0, 0, 1, 0]),
  array([0, 0, 0, 1, 0]),
  array([1, 0, 1, 1, 0])])

In [ ]:
#RBM algorithm

In [ ]:
def sig(x):
  return 1/(1+np.exp(-x))

In [ ]:
sig(np.array([0, 10]))

array([0.5      , 0.9999546])

In [ ]:
b = np.zeros(len(V[0]))
c = np.zeros(len(H[0]))
W = np.zeros((len(H[0]), len(V[0])))

In [ ]:
0.1*W.dot(V[1])

array([0., 0., 0., 0., 0.])

In [ ]:
np.transpose(np.array([(W.dot(V[i]) + c)])).dot(np.array([V[i]])).shape, W.shape

((5, 46), (5, 46))

In [ ]:
n = len(V)

In [ ]:
k = 3
eta = 0.1
#print(b.shape, c.shape, W.shape)
for i in range(1000):
  h_til = sig(W.dot(V[i]) + c)
  for j in range(k):
    v_til = sig(np.transpose(W).dot(h_til) + b)
    h_til = sig(W.dot(v_til) + c)
  W = W + eta*(np.transpose(np.array([(W.dot(V[i]) + c)])).dot(np.array([V[i]])) - np.transpose(np.array([sig(W.dot(v_til) + c)])).dot(np.array([v_til])))
  b = b + eta*(V[i]-v_til)
  c = c + eta*(sig(W.dot(V[i]) + c) - sig(W.dot(v_til) + c))
  print(i*100/n)

0.0
0.00039419741406496373
0.0007883948281299275
0.0011825922421948912
0.001576789656259855
0.001970987070324819
0.0023651844843897824
0.0027593818984547464
0.00315357931251971
0.003547776726584674
0.003941974140649638
0.004336171554714601
0.004730368968779565
0.005124566382844528
0.005518763796909493
0.005912961210974456
0.00630715862503942
0.006701356039104383
0.007095553453169348
0.007489750867234311
0.007883948281299276
0.008278145695364239
0.008672343109429203
0.009066540523494166
0.00946073793755913
0.009854935351624093
0.010249132765689057
0.01064333017975402
0.011037527593818985
0.011431725007883949
0.011825922421948912
0.012220119836013876
0.01261431725007884
0.013008514664143803
0.013402712078208767
0.01379690949227373
0.014191106906338695
0.014585304320403659
0.014979501734468622
0.015373699148533586
0.01576789656259855
0.016162093976663513
0.016556291390728478
0.01695048880479344
0.017344686218858405
0.017738883632923367
0.018133081046988332
0.018527278461053294
0.018921475

<ipython-input-26-fd26cb9c1a68>:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


0.024834437086092714
0.02522863450015768
0.025622831914222644
0.026017029328287606
0.02641122674235257
0.026805424156417533
0.027199621570482498
0.02759381898454746
0.027988016398612425
0.02838221381267739
0.028776411226742352
0.029170608640807318
0.02956480605487228
0.029959003468937245
0.030353200883002206
0.03074739829706717
0.031141595711132133
0.0315357931251971
0.031929990539262064
0.032324187953327026
0.03271838536739199
0.033112582781456956
0.03350678019552192
0.03390097760958688
0.03429517502365184
0.03468937243771681
0.03508356985178177
0.035477767265846734
0.0358719646799117
0.036266162093976664
0.036660359508041626
0.03705455692210659
0.03744875433617156
0.03784295175023652
0.03823714916430148
0.03863134657836645
0.03902554399243141
0.03941974140649637
0.039813938820561334
0.0402081362346263
0.040602333648691265
0.04099653106275623
0.041390728476821195
0.04178492589088616
0.04217912330495112
0.04257332071901608
0.04296751813308105
0.04336171554714601
0.04375591296121097
0.0

In [ ]:
W, b, c

(array([[-2.90920313e+133, -3.46917351e+134, -3.07508344e+134,
         -8.93941313e+134, -1.11374103e-001, -1.66460834e+134,
         -7.27480646e+134, -6.58116510e+134, -8.56790023e+134,
         -2.91288151e+134, -4.96827530e+134, -2.50398436e+134,
         -5.59129741e+130],
        [-2.90920313e+133, -3.46917351e+134, -3.07508344e+134,
         -8.93941313e+134, -1.11374103e-001, -1.66460834e+134,
         -7.27480646e+134, -6.58116510e+134, -8.56790023e+134,
         -2.91288151e+134, -4.96827530e+134, -2.50398436e+134,
         -5.59129741e+130],
        [-2.90920313e+133, -3.46917351e+134, -3.07508344e+134,
         -8.93941313e+134, -1.11374103e-001, -1.66460834e+134,
         -7.27480646e+134, -6.58116510e+134, -8.56790023e+134,
         -2.91288151e+134, -4.96827530e+134, -2.50398436e+134,
         -5.59129741e+130],
        [-2.90920313e+133, -3.46917351e+134, -3.07508344e+134,
         -8.93941313e+134, -1.11374103e-001, -1.66460834e+134,
         -7.27480646e+134, -6.5811